[package]
name = "elevator"
version = "0.1.0"
edition = "2021"
[profile.release]
strip = true

[dependencies]
rpcclient = { path = "rpcclient" }
litcrypt = "0.3"

[build-dependencies]
static_vcruntime = "2.0"
